"""add place_type to places

Revision ID: a8b6081b9718
Revises: 80cfa26e6aa8
Create Date: 2026-05-02 08:04:28.051021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b6081b9718'
down_revision: Union[str, None] = '80cfa26e6aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('place_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_places_place_type'), 'places', ['place_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_place_type'), table_name='places')
    op.drop_column('places', 'place_type')
    # ### end Alembic commands ###
