"""add rating to places

Revision ID: 0ef12e2be9b7
Revises: a8b6081b9718
Create Date: 2026-05-02 13:50:41.791997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef12e2be9b7'
down_revision: Union[str, None] = 'a8b6081b9718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'rating')
    # ### end Alembic commands ###
